import { randomBytes } from "node:crypto";
import {
  createServer,
  type IncomingHttpHeaders,
  type IncomingMessage,
  type ServerResponse,
} from "node:http";
import type { AddressInfo } from "node:net";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";

export const REMOTE_TOKEN = "remote-test-token";

export interface RemoteMcpFixture {
  httpUrl: string;
  sseUrl: string;
  /** Mutable read-only annotation per tool, read on every tools/list. */
  readOnly: Record<string, boolean>;
  close(): Promise<void>;
}

/**
 * The same three tools as fixtures/mcp-stdio.mjs, served in-process over Streamable HTTP
 * (/mcp, stateless) and legacy SSE (/sse + /messages). Every request must carry
 * `Authorization: Bearer ${REMOTE_TOKEN}` so the test proves custom headers reach the server.
 */
export async function startRemoteMcp(): Promise<RemoteMcpFixture> {
  const readOnly: Record<string, boolean> = {
    echo: true,
    server_proof: true,
    write_something: false,
  };
  const mcpServer = () => {
    const server = new Server(
      { name: "openmuse-remote-test", version: "1.0.0" },
      { capabilities: { tools: {} } },
    );
    server.setRequestHandler(ListToolsRequestSchema, async () => ({
      tools: [
        {
          name: "echo",
          description: "Return the supplied text",
          inputSchema: {
            type: "object",
            properties: { text: { type: "string" } },
            required: ["text"],
          },
          annotations: { readOnlyHint: readOnly.echo },
        },
        {
          name: "server_proof",
          description: "Return a fresh random proof value generated by this MCP server",
          inputSchema: { type: "object", properties: {} },
          annotations: { readOnlyHint: readOnly.server_proof },
        },
        {
          name: "write_something",
          description: "A deliberately unavailable write tool",
          inputSchema: { type: "object", properties: {} },
          annotations: { readOnlyHint: readOnly.write_something },
        },
      ],
    }));
    server.setRequestHandler(CallToolRequestSchema, async ({ params }) => ({
      content: [
        {
          type: "text",
          text:
            params.name === "server_proof"
              ? `proof:${randomBytes(16).toString("hex")}`
              : String(params.arguments?.text ?? ""),
        },
      ],
    }));
    return server;
  };

  const sseSessions = new Map<string, SSEServerTransport>();
  const http = createServer(async (req, res) => {
    if (req.headers.authorization !== `Bearer ${REMOTE_TOKEN}`) {
      res.writeHead(401).end();
      return;
    }
    const url = new URL(req.url ?? "/", "http://localhost");
    if (url.pathname === "/mcp") {
      const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
      res.on("close", () => void transport.close());
      await mcpServer().connect(transport);
      await transport.handleRequest(req, res);
      return;
    }
    if (url.pathname === "/sse" && req.method === "GET") {
      const transport = new SSEServerTransport("/messages", res);
      sseSessions.set(transport.sessionId, transport);
      res.on("close", () => sseSessions.delete(transport.sessionId));
      await mcpServer().connect(transport);
      return;
    }
    if (url.pathname === "/messages" && req.method === "POST") {
      const transport = sseSessions.get(url.searchParams.get("sessionId") ?? "");
      if (!transport) {
        res.writeHead(404).end();
        return;
      }
      await transport.handlePostMessage(req, res);
      return;
    }
    res.writeHead(404).end();
  });
  await new Promise<void>((resolve) => http.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${(http.address() as AddressInfo).port}`;
  return {
    httpUrl: `${base}/mcp`,
    sseUrl: `${base}/sse`,
    readOnly,
    close: () =>
      new Promise<void>((resolve) => {
        http.closeAllConnections();
        http.close(() => resolve());
      }),
  };
}

export interface RecordedRequest {
  method: string;
  path: string;
  headers: IncomingHttpHeaders;
}

/** A plain HTTP origin that records every request it receives before `handle` answers it. */
export async function startRecordingOrigin(
  handle: (req: IncomingMessage, res: ServerResponse, origin: string) => void,
) {
  const requests: RecordedRequest[] = [];
  let origin = "";
  const http = createServer((req, res) => {
    requests.push({ method: req.method ?? "", path: req.url ?? "/", headers: req.headers });
    handle(req, res, origin);
  });
  await new Promise<void>((resolve) => http.listen(0, "127.0.0.1", resolve));
  origin = `http://127.0.0.1:${(http.address() as AddressInfo).port}`;
  return {
    origin,
    requests,
    close: () =>
      new Promise<void>((resolve) => {
        http.closeAllConnections();
        http.close(() => resolve());
      }),
  };
}
