import { randomBytes } from "node:crypto";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";

const server = new Server(
  { name: "openmuse-test", version: "1.0.0" },
  { capabilities: { tools: {} } },
);
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "echo",
      description: "Return the supplied text",
      inputSchema: { type: "object", properties: { text: { type: "string" } }, required: ["text"] },
      annotations: { readOnlyHint: true },
    },
    {
      name: "server_proof",
      description: "Return a fresh random proof value generated by this MCP server",
      inputSchema: { type: "object", properties: {} },
      annotations: { readOnlyHint: true },
    },
    {
      name: "write_something",
      description: "A deliberately unavailable write tool",
      inputSchema: { type: "object", properties: {} },
      annotations: { readOnlyHint: false },
    },
  ],
}));
server.setRequestHandler(CallToolRequestSchema, async ({ params }) => ({
  content: [
    {
      type: "text",
      text:
        params.name === "server_proof"
          ? `proof:${randomBytes(16).toString("hex")}`
          : String(params.arguments?.text ?? ""),
    },
  ],
}));
await server.connect(new StdioServerTransport());
